### ISSUE TITLE
[Feature Request] Option to make the picker always on top of other windows

### ISSUE THREAD

**Issue by rp1231** [aloneguid/bt#101]
If you are invoking the browser tamer picker from an "Always on top" window, like the media player potplayer, The picker gets hidden underneath the window and is not accessible especially if you are using the Close on focus loss option.

An option to make the picker always on top of other windows would help solve this problem.

**Comment by aloneguid** [comment]
Is [this](https://aloneguid.github.io/bt/picker.html#other-customisations) what you are looking for?
