### ISSUE TITLE
Browser picker is shown even if rule is matched

### ISSUE THREAD

**Issue by latonita** [aloneguid/bt#105]
Hi,
I have just started using BT and I like when it shows a browser picker, but i tried to use rules and it still shows me a picker window.
Ver 4.2.0, ImGui 1.91.0

What I assumed:
- when rule is matched, then URL will be opened in this particular browser, without asking a user

What happens:
- i see browser picker window

Example: 
I added `app.manatal.com` to my work browser rules (tried two different ways)
![image](https://github.com/user-attachments/assets/b5d81779-d223-454a-8fba-d3722177c496)
Saved the configuration.

Here is Pipeline debugger:
![image](https://github.com/user-attachments/assets/cf7eb61c-8f15-4c41-850c-b6a623a013d6)

Then I go to slack, click a link to app.manatal.com... and I see browser selector
![image](https://github.com/user-attachments/assets/7d1ade51-ef77-40e2-985e-81868ff5bd61)

**Comment by latonita** [comment]
@aloneguid unfortunately this is not the case, i had one rule first, then i added one more. 
Now I only have one rule and it doesnt work.
This is the only rule i have in the system.
![image](https://github.com/user-attachments/assets/8bc84ef5-0aa9-4ed3-9e9c-e589c8d581cf)

**Comment by aloneguid** [comment]
Just checking picker is not set to "always"? https://aloneguid.github.io/bt/picker.html

**Comment by latonita** [comment]
@aloneguid you made my day! It was set to 'Always'.
I changed it to 'conflict' + 'no rule'.
It works now, thanks a lot!!
