### ISSUE TITLE
Doesn't work on Windows 8.1

### ISSUE THREAD

**Issue by Katarn** [aloneguid/bt#110]
Hello. To run the application required the following libraries:

- api-ms-win-core-file-l1-2-2.dll
- api-ms-win-core-file-l2-1-2.dll
- api-ms-win-core-heap-l2-1-0.dll

I download them from dllme.com. But then another error appeared:

> The procedure entry point GetDpiForSystem could not be located in the dynamic link library bt.exe

The GetDpiForSystem function [appeared in Windows 10](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getdpiforsystem).

It seems to me that this is a very strange dependence on the version of Windows. Nothing specific that is necessary for its operation comes to my mind. And I couldn't find the minimum system requirements.

I tred 4.2.0 version.

**Comment by aloneguid** [comment]
Im sorry but windows 8 is not supported by Microsoft anymore so I can't even build a binary for it on github.

**Comment by Katarn** [comment]
It just sounds a little strange to me - now people write mostly cross-platform software, and here even within one platform there are some restrictions. Do I understand correctly that the problem is not in the application itself, but in the fact that GitHub Actions does not support Windows 8.1?

**Comment by aloneguid** [comment]
Yes, github only provides not out of life oses. It's possible to add self hosted build agent but I personally won't be able to c9btribute time to support a dead os and host it. Of course you are welcome to build it yourself as all code and build pipelines are completely open.

**Comment by aloneguid** [comment]
Also keep in mind most modern dev tooling won't run on anything less than windows 10, which was released almost 10 years ago by the way.

**Comment by Katarn** [comment]
It's understandable, it's just hard to wrap my head around the fact that modern software only works on 2 versions of Windows :) It seems that for the first time in history, the simplest software is so tied to the OS version (i'm not just talking about bt). I live in a world where the same software works on Windows, Linux, MacOS, Haiku, and some on Android and iOS, and I find it hard to understand.

Well, thanks for the answer.

**Comment by Katarn** [comment]
If anyone googles this issue, I found a working alternative. If the author bt doesn't mind, I'll leave the link: https://github.com/stuartleeks/pick-a-browser

**Comment by aloneguid** [comment]
Sure feel free to share. There are many versions of windows 10 and 11. Probably the first version of bt will work with 8. But I would encourage you to upgrade. 

As this is a system utility it heavily relies on windows internals hence not cross platform. The only cross platform part is user interface .
