### ISSUE TITLE
Add option to clear URLs

### ISSUE THREAD

**Issue by MuntashirAkon** [aloneguid/bt#113]
I stumbled upon this project as I was looking for a desktop alternative to [URLCheck](https://github.com/TrianguloY/URLCheck). This app, overall, seems like it's going towards the right direction. However, it lacks one privacy features: cleaning the tracking parameters from an URL (except MS 365). ClearURLs project maintains a catalog of such tracking parameters which you can find here: https://docs.clearurls.xyz/latest/specs/rules/

Thanks for your time and consideration, and good luck on your project.

**Comment by aloneguid** [comment]
Hi. Sorry, but this is not the purpose of this utility. If you have an extermal utility that can do that, you can always invoke it with a Lua script, or write the logic yourself in Lua and contribute back.

**Comment by MuntashirAkon** [comment]
> Sorry, but this is not the purpose of this utility.

You do offer cleaning the URLs for MS 365 links.

> write the logic yourself in Lua and contribute back.

So, are you open to adding such features to BT if implemented by others?

**Comment by aloneguid** [comment]
Unwrapping for O365 is essential in order to apply a rule, that's why it's there. Of course I'm open to PRs, when they make sense. You can implement it either in C++ or Lua, but the latest is preferred, so it's stays outside of the main purpose.
