### ISSUE TITLE
Links in Outlook do not work

### ISSUE THREAD

**Issue by mohnen** [aloneguid/bt#12]
I am using Microsoft® Outlook® für Microsoft 365 MSO (Version 2208 Build 16.0.15601.20676) 64 Bit
This is part of Microssoft 365 for Enterprise.
When I click a link in an Outlook item (message, calender, ...) this error occurs

"Unexpectedd error for URL ... Access denied"

**Comment by aloneguid** [comment]
Can you give a sample URL you're trying to open please.

**Comment by mohnen** [comment]
Any URL will do; I assume that Outlook tries some kind of pre-loading and fails with it.

<img width="792" alt="test" src="https://github.com/aloneguid/bt/assets/4920720/b7306658-5a1b-40f1-8667-766a172ab759">

**Comment by aloneguid** [comment]
Do you mind sharing `config.ini` (File->config.ini)?

**Comment by mohnen** [comment]
Not at all :)
[config.ini.txt](https://github.com/aloneguid/bt/files/12000496/config.ini.txt)

**Comment by aloneguid** [comment]
i can't download it - error.

**Comment by mohnen** [comment]
`theme = corp_grey


[browser:chrome]
name = Google Chrome
cmd = C:\Program Files\Google\Chrome\Application\chrome.exe
vdf = Google\Chrome\User Data
subtype = chromium


[browser:chrome:Default]
name = Markus
arg = "%url%" "--profile-directory=Default"
icon = C:\Users\mmohnen\AppData\Local\Google\Chrome\User Data\Default\Google Profile Picture.png
cmd = C:\Program Files\Google\Chrome\Application\chrome.exe
home = C:\Users\mmohnen\AppData\Local\Google\Chrome\User Data\Default


[browser:msedge]
name = Microsoft Edge
cmd = C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
vdf = Microsoft\Edge\User Data
subtype = chromium


[browser:msedge:Default]
name = Geschäftlich
arg = "%url%" "--profile-directory=Default"
icon = C:\Users\mmohnen\AppData\Local\Microsoft\Edge\User Data\Default\Edge Profile Picture.png
cmd = C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
home = C:\Users\mmohnen\AppData\Local\Microsoft\Edge\User Data\Default
rule = aixtron.com
rule = aixcloud.sharepoint.com
`

**Comment by aloneguid** [comment]
Thanks, seems to be nothing wrong here. What we can try to debug further:
1. Open `config.ini`.
2. Shutdown all BT instances (right-click tray icon and press "Exit" if needed).
3. Add the following line somewhere in the beginning of the file: `flag_debug_args=y`. It should look something like:

![image](https://github.com/aloneguid/bt/assets/3155189/6abb1c50-88cf-4719-93b4-f07b25f1bc69)

4. Download and install [this version](https://github.com/aloneguid/bt/suites/14181473719/artifacts/795089493) (you may want to backup `config.ini`).
5. Launch and go to `Tools->Rediscover Browsers`.
6. Try clicking the link again from Outlook, and send me screenshot, which should look like:

![image](https://github.com/aloneguid/bt/assets/3155189/2073b961-2ea0-4fa8-9e7a-29863749fc64)

**Comment by mohnen** [comment]
There is no popup except the error message from Outlook. 
It seems that Outlook fails even before launching bt.exe

**Comment by aloneguid** [comment]
Odd. Are you able to open links from any other desktop app with BT? Just wondering if this is Outlook specific. 

I'm wondering if this is related https://superuser.com/questions/1407898/error-something-unexpected-went-wrong-with-this-url-in-outlook

**Comment by mohnen** [comment]
All other apps work fine. Changing the default browser and back did not
work.

**Comment by mohnen** [comment]
I found it, it's not your programs fault; it's my companies paranoid Windows Defender settings 
![2023-07-12 16_21_51-Window](https://github.com/aloneguid/bt/assets/4920720/441e27c5-ad7c-490c-8940-cfac24274668)
