### ISSUE TITLE
[Non-Repo] Scoop broken

### ISSUE THREAD

**Issue by NoPlagiarism** [aloneguid/bt#14]
[Link to bt bucket](https://github.com/ScoopInstaller/Extras/blob/0febb56f8041967f8f3318d8e5de2a74f409fdf0/bucket/bt.json)

CheckVer and AutoUpdate are linked to `https://www.aloneguid.uk/projects/bt/bin/`

Those urls doesn't seem to work anymore

**Comment by aloneguid** [comment]
Binaries are built and hosted fully on GitHub now. The best bet is downloading MSI or zip from here.

Unfortunately scoop makes a lot of assumptions that I don't have time to deal with, but I'd be happy if someone supports scoop.

**Comment by aloneguid** [comment]
Actually I have decided to remove BT from all package managers, PRs for [winget](https://github.com/microsoft/winget-pkgs/pull/115266) and [scoop](https://github.com/ScoopInstaller/Extras/pull/11695) are open.
