### ISSUE TITLE
[RFE] Make Browser Tamer available on Chocolatey.

### ISSUE THREAD

**Issue by claudio-salvio** [aloneguid/bt#19]
Hello @aloneguid 

Please make Browser Tamer can be installed using [Chocolatey](https://chocolatey.org).
[Chocolatey](https://community.chocolatey.org) is probably the most used package manager on Windows.
Making it available there will be beneficial both for Choco users and for making [Browser Tamer](https://www.aloneguid.uk/projects/bt/) known to more people.
Thank you very much for Browser Tamer, I consider it a very useful software.

Kind regards,
Claudio Salvio

**Comment by aloneguid** [comment]
It's just the physical lack of time. I can only see it happening if someone likes to take ownership of publishing to package managers.

**Comment by gbakeman** [comment]
I totally understand. I'm only suggesting that the issue be reopened in case someone else wants to pick it up.
