### ISSUE TITLE
Frameless window

### ISSUE THREAD

**Issue by D3XX3R** [aloneguid/bt#20]
Frameless window is not supported by firefox but it's still activated by default.
Would it be possible to have an option in the config to have it enabled/disabled by default?

**Comment by D3XX3R** [comment]
In the Pick a Browser window

**Comment by aloneguid** [comment]
I see, thanks. It's only displayed there because I don't know which browser you are going to choose. I can fix this, thanks.

**Comment by aloneguid** [comment]
Fixed in 3.4 ;)

**Comment by danarnold** [comment]
Was D3XX3R's idea of a way to configure whether the frameless window option is enabled or disabled by default ever implemented? I use the chooser for all links and now all my Chrome links default to opening in a frameless window, but I'd like to be able to configure it so that it opens in the normal browser by default instead.

**Comment by D3XX3R** [comment]
It seems like it was disabled after the update but when you use it just once it goes back to enabled by default.

**Comment by aloneguid** [comment]
It will be in whatever state you have used it last time.
You can also set the flag per rule.

**Comment by danarnold** [comment]
It's definitely not the case for me that it uses the state from last time. Each time, it defaults to opening in a frameless window for my Chrome browser, even though I keep toggling it off.

I'm not using any rules at all, so it wouldn't be rules affecting anything, nor would they be able to help. I'm using the chooser for all links.

**Comment by danarnold** [comment]
@aloneguid Hope I'm not being annoying, if so I apologize – any updates on making frameless windows not be the default for Chrome in the chooser? Should I make a new issue?

**Comment by aloneguid** [comment]
Sorry no promises here, it's a hobby project with no time commitments ;)

**Comment by danarnold** [comment]
> Sorry no promises here, it's a hobby project with no time commitments ;)

Absolutely, I totally understand which is why I didn't want to come off as nagging. I appreciate your reply & reopening the issue.

**Comment by aloneguid** [comment]
@danarnold please check v3.4.2, i think this is resolved now.

**Comment by aloneguid** [comment]
brilliant ;) i appreciate if you can star the project - really helps
