### ISSUE TITLE
Undefined

### ISSUE THREAD

**Issue by neoOpus** [aloneguid/bt#31]
Something is broken, when I click the icon it sets the URL to http://undefined/

**Comment by aloneguid** [comment]
Could you give me more context and a screenshot please?

**Comment by neoOpus** [comment]
Previous version works just fine!

**Comment by aloneguid** [comment]
Most probably! When the picker is shown, which URL can you see in "copy&close" button here?

<img width="593" alt="image" src="https://github.com/aloneguid/bt/assets/3155189/23ae0e7e-d9f2-4f30-a0bd-4f536109ca81">

Is it also undefined?

**Comment by neoOpus** [comment]
Yes it is 

![image](https://github.com/aloneguid/bt/assets/1388336/cef99a8f-15e9-45db-8853-739fec0d7253)

**Comment by aloneguid** [comment]
Yes, it needs "tabs" permission which I removed (wasn't required for right-click). I've added it back and just waiting for Chrome Store to publish it (v1.3).

**Comment by aloneguid** [comment]
It's published, hope it works now )

**Comment by neoOpus** [comment]
Thank you, I was about to do the fix myself today, but you were way faster than I was. :)

**Comment by aloneguid** [comment]
Feel free to add other features, I'm terrible with JavaScript ;)
