### ISSUE TITLE
Feature req: custom icon for .bat launchers

### ISSUE THREAD

**Issue by Virgus** [aloneguid/bt#33]
Hello, this tool is really great. Lots of improvements since last time I passed by !

I'm trying to set it according to my needs and I have one feature request for the upcoming updates.

My main browser is launched "clean" from ram and I used a .bat (or .cmd) script for the launcher (to copy it to ram and start the real launcher with the correct settings - mainly I use the options to launch it googled or ungoogled). I tried assigning the icon in the main browser declaration config.ini but the icon is not taken into account.

```
[browser:chrlauncher]
name = ChromeX Portable
cmd = C:\PortableApps\Internet Browsers\ChromeX\Chromium Portable\chrlauncher.exe
hidden = n

[browser:chrlauncher:default]
name = Default
arg = "%url%"
icon = C:\PortableApps\Internet Browsers\ChromeX\Chromium Portable\chrlauncher.exe
rule = scope:domain|rsload.net


[browser:chromexram]
name = ChromeX RAM Portable
cmd = C:\PortableApps\Internet Browsers\ChromeX\CX2RAM.bat
icon = C:\PortableApps\Internet Browsers\ChromeX\CX2RAM.ico
hidden = n

[browser:chromexram:default]
name = Default
arg = "%url%"
icon = C:\PortableApps\Internet Browsers\ChromeX\CX2RAM.ico
rule = scope:domain|rsload.net
```

It's just an aesthetic issue because overall it's actually working, but it would be great to personalize the browsers main icons if possible. Consider that I use several versions of chromium with their default profile and I'd love to have them distinguishable at first glance by using a specific icon for each of them.

Thanks and have a great day !

![20230817_103450_Snapshot_bt](https://github.com/aloneguid/bt/assets/6388217/a7ab7872-3025-407e-875f-b70412a47e74)

**Comment by aloneguid** [comment]
This is coming in v4, you should be able to change icons for profile and a browser:

![image](https://github.com/aloneguid/bt/assets/3155189/1a8303ec-b8c2-4c75-9ca6-7c75a1d0d67f)

**Comment by aloneguid** [comment]
You can now do this in v4.

**Comment by Virgus** [comment]
> You can now do this in v4.

Amazing !!! Thanks, a fix that is a nice surprise indeed !
Have a nice summer !
V.
