### ISSUE TITLE
Not a cheap bastard

### ISSUE THREAD

**Issue by neoOpus** [aloneguid/bt#35]
I apologize, but I am unable to make a donation at this time. However, I will make a donation as soon as I am in a dire financial situation (no income) and able to do so. I sincerely appreciate the amount of work you've done on this software and the quality of it.

**Comment by aloneguid** [comment]
No worries, i'm not expecting anything. You should have seen this in a temporary branch, but let me know if the silly message appears elsewhere as it might be offensive.
Thanks for being an active user, that's much better than donations ;)
