### ISSUE TITLE
Feature: Spawn Picker on active display instead of main display

### ISSUE THREAD

**Issue by mahoromax** [aloneguid/bt#42]
Currently, when I open a link on my 2nd screen, the picker appears in the middle of my main screen - possibly on top of a movie or game that is currently running - and I need to move my mouse to the other screen and then back.

**Comment by aloneguid** [comment]
Scheduled for v3.6. You can test dev version at https://github.com/aloneguid/bt/actions/runs/6147403588

**Comment by aloneguid** [comment]
3.6.0 is out with the fix.

**Comment by mahoromax** [comment]
This behaviour has resurfaced.
BT always opens on main monitor for me. I'm on 4.0.2 but I didn't see anything on 4.0.3 rls notes about this.
