### ISSUE TITLE
Thorium support

### ISSUE THREAD

**Issue by paz** [aloneguid/bt#43]
I was about to make a pull request when I read you don't accept them. It seems simple enough to add support for other Chromium based browsers, is it possible to add support for Thorium?

I have been using the "add browser" function but it does not support different profiles.

Links:

https://thorium.rocks/

https://github.com/Alex313031/thorium

**Comment by paz** [comment]
As an extension to this, maybe it is possible to have this configurable via the UI? So we can add any chromium based browser by specifying the User Data and System ID to enable the full feature set for them.

**Comment by paz** [comment]
I was able to resolve my use case by editing the config.ini. I didn't realise I could do this from there. It would still be nice if adding the browser through the UI autodiscovered the profiles though.

**Comment by aloneguid** [comment]
Thanks, will schedule for next release. Reason for not accepting PR is testing - it takes much more time than adding code.

**Comment by aloneguid** [comment]
and thanks for Thorium - i didn't know it exists ;)

**Comment by neoOpus** [comment]
> Thanks, will schedule for next release. Reason for not accepting PR is testing - it takes much more time than adding code.

I can help with that if you would like. You just need to let me know how.

**Comment by aloneguid** [comment]
> > Thanks, will schedule for next release. Reason for not accepting PR is testing - it takes much more time than adding code.
> 
> I can help with that if you would like. You just need to let me know how.

Baiscally compiling and testing it on a clean workstation. You could probably just test binaries generated by PR builds as well.

Thorium is coming btw ;)

![image](https://github.com/aloneguid/bt/assets/3155189/461da9e2-fa3e-4ec6-a6ec-44a30140701e)

**Comment by aloneguid** [comment]
3.6.0 is out with the fix.
