### ISSUE TITLE
Not Redirecting Notifications

### ISSUE THREAD

**Issue by CityguyUSA** [aloneguid/bt#45]
I'm not sure if notifications are operating on a different protocol or what but they don't open in the correct browser.

**Comment by aloneguid** [comment]
It's very much application specific. Can you give more details please.

**Comment by CityguyUSA** [comment]
I'm not exactly sure what you're asking me but I'll do my best. 

Websites are allowed to send notifications based on your allowing them.  In my case the notifications were set-up through Vivaldi which is a Chrome derivative.   I'm running Win10x64.   I have the notification URLs set to open in Chrome but they still open in Vivaldi.  I cannot actually see the URL of the notification they may be getting redirected. 

I was able to click on email links and have them open the proper browser but they have since just stopped working entirely.  I closed and reopened my email hoping to resolve problem but with no such luck.  I can't open any links in my email regardless of the browser,

I noted that there are 20 instances of BT running in task manager but I can't account for what those 20 processes are doing.  I only have 10 tabs total between my 2 browsers.

If I try to open BT directly to check settings etc it won't open.  I did verify that the defaults for the protocols are still set properly,  At one point there was an icon in the tray area but it's not currently there.

I'm using the BT.zip install.

**Comment by CityguyUSA** [comment]
Can't close Chrome browser.  It keeps reopening I guess with a redirected tab.

**Comment by aloneguid** [comment]
This looks like something like an antivirus is interfering. BT should run exactly 1 process at all times. Which antivirus are you using and which BT version?

**Comment by CityguyUSA** [comment]
Microsoft Defender BT 3.5.2

When I started my computer today.  I clicked on an email link then some notifications.  It didn't redirect like it had the day before.  I checked to see if it was running.  BT already had 3 processes running.  I was able to open one email link and then nothing.  But it wouldn't let me close my browser again kept restarting it.  I tried to terminate BT but it just added another process.  I was able to get ahead of it using an aggressive kill and I deleted it form my hard drive.

**Comment by aloneguid** [comment]
Maybe try the latest version. Hard to guess without having more details.

**Comment by ianzhuo** [comment]
Toash Notification from browser are handled by `notification_helper.exe` in every chrome based browser.
and registry is in `HKEY_CLASSES_ROOT\CLSID\{635EFA6F-08D6-4EC9-BD14-8A0FDE975159}`

Maybe Browser Tamer could consider add a notification_helper_proxy to redirect Toast Notification Click in Windows Notification Center.

**Comment by aloneguid** [comment]
I'm trying to get my head around what you are trying to achieve. Notifications from a browser usually relate to a page or app inside that browser, right? If you are clicking on them, they are going to handle some action inside that browser, not opening an URL. I'm not sure what we can do here?

**Comment by ianzhuo** [comment]
Hi,
If disable system notifications in `chrome://flags/`, then notifications click will be handled directly from browser.
![image](https://github.com/aloneguid/bt/assets/1394735/6bcdf62e-db8c-4ec7-89a0-e55e89cf37be)
![image](https://github.com/aloneguid/bt/assets/1394735/aa9c97e1-807e-45a3-9954-26c13a16a4c6)
If enable system notifications in `chrome://flags/`, then notifications will be took over by Windows Action Center and clicked will be handle by `notification_helper.exe`.
![image](https://github.com/aloneguid/bt/assets/1394735/90b59b76-4c83-4e5a-854b-25c49adb0f8a)
![image](https://github.com/aloneguid/bt/assets/1394735/4a7e0a50-490c-4aaa-a951-6213417f2ee8)
