### ISSUE TITLE
When using dual monitors, picker always shows on position

### ISSUE THREAD

**Issue by ianzhuo** [aloneguid/bt#48]
Hi, I'm using browser tamer 3.6.
When clicking link on monitor 1, the picker shows on monitor 2.
and clicked link on monitor 2, the picker shows on monitor 1.

**Comment by aloneguid** [comment]
Is your primary monitor set to exernal monitor by any chance? ;) I might have a good idea where the bug is.

**Comment by ianzhuo** [comment]
Yes, I did set my primary monitor to my external monitor.  😃

**Comment by aloneguid** [comment]
Yep I think I've screwed it up ;) Will release a fix soon.

**Comment by aloneguid** [comment]
please check v3.6.1

**Comment by ianzhuo** [comment]
After upgradeing to ver. 3.6,  everything works fine, Thank you.

**Comment by aloneguid** [comment]
Thank you!
