### ISSUE TITLE
Application error on startup

### ISSUE THREAD

**Issue by NicholasBoll** [aloneguid/bt#5]
I'm excited for this application, but I can't seem to get it to start. Here's the log from Windows Event Viewer: Application

```log
Faulting application name: bt.exe, version: 3.1.6.0, time stamp: 0x649d68f7
Faulting module name: bt.exe, version: 3.1.6.0, time stamp: 0x649d68f7
Exception code: 0xc0000005
Fault offset: 0x000000000004ca88
Faulting process id: 0x0x86E0
Faulting application start time: 0x0x1D9AB7DF77A9645
Faulting application path: C:\Program Files\Browser Tamer\bt.exe
Faulting module path: C:\Program Files\Browser Tamer\bt.exe
Report Id: 93b5c747-409d-4d5d-bbed-d53faf687b75
Faulting package full name: 
Faulting package-relative application ID: 
```

I'm running Windows 11. Windows Specifications:
```
Edition	Windows 11 Pro
Version	22H2
Installed on	‎9/‎19/‎2022
OS build	22621.1926
Experience	Windows Feature Experience Pack 1000.22644.1000.0
```

I'm running Windows PowerToys 0.70.1. I have Chrome, Edge, and Firefox browsers installed. I'm not sure what other information would be relevant.

**Comment by NicholasBoll** [comment]
I tried 3.1.1 by using the zip and the exe. After manually dismissing all the Windows Defender warnings, the application is running.

**Comment by maluht** [comment]
I have the same problem, based on your input Nicholas I also went with version 3.1.1 that also works for me.

**Comment by aloneguid** [comment]
Thanks for reporting this, I could reproduce it. Could you try 3.1.7 please?

**Comment by NicholasBoll** [comment]
I'll clarify a bit more. I manually ran 3.1.1 and it started up just fine. After defining some rules, 3.1.6 started running fine. I think 3.1.7 fixed the issue by not crashing without proper configuration of at least 1 browser register - which wouldn't effect existing users, only new users.

I've upgraded to 3.2.0 and everything seems to be working. I'll close the issue. Thanks for the quick fix!

**Comment by aloneguid** [comment]
Exactly, I never tested on a new install this time. Usually I'd launch it in Windows Sandbox before releasing.

If my assistance was star-worthy, feel free to sprinkle some stardust on my project—it's like giving it a high-five from the universe! ✨
