### ISSUE TITLE
Unable to display Chinese characters

### ISSUE THREAD

**Issue by ianzhuo** [aloneguid/bt#50]
Hi, it seems not able to display Chinese characters in bt for now, could you please cosider adding that feature for non-us users, thx.

![image](https://github.com/aloneguid/bt/assets/1394735/1eb15abd-fb05-44e8-a541-3f0dd4df351d)
![image](https://github.com/aloneguid/bt/assets/1394735/ec9c4091-b706-42eb-ac45-c7f31e2c6aef)

**Comment by PsychodelEKS** [comment]
It would`ve been great to support UTF8
Not that I often open BT to reconfigure or absolutely can not understand what`s under the ?????, but still =)
Though if it`s pain to implement, it won't stop me from using BT.

![image](https://github.com/user-attachments/assets/4bc95f51-1640-4529-b8af-cadee2449a83)
