### ISSUE TITLE
Scoop persist broken

### ISSUE THREAD

**Issue by neoOpus** [aloneguid/bt#52]
Ivan,

For some reason, the "persist" feature does not function as intended. The config.ini file is both written to and read from the executable's directory. However, when an update occurs, the settings are lost.
The bt.ini file is created, and the files still exist, but they are currently not being utilized.

**Comment by aloneguid** [comment]
It came down to [this](https://github.com/aloneguid/bt/discussions/26). Scoop has decided to keep a broken version, but I'm not behind the decision.
