### ISSUE TITLE
Open in Browser Tamer should show the choose browser windows

### ISSUE THREAD

**Issue by ajhvdb** [aloneguid/bt#54]
Installed Browser Tamer (default = Chrome)
Installed in Chrome the extension

What i expected what would happen that the icon "Open in Browser Tamer" or right-menu on a link> "Open in Browser Tamer" would open the browser chooser?

Did i set this up correctly or can i modify the extension to work like this?

**Comment by aloneguid** [comment]
Chrome extension simply sends the link to Browser Tamer, and it handles the link depending on configuration you have created.

If your default browser is Chrome and there are no rules configured, it will just open the link in Chrome, which is what is happening anyway from my understanding?

You can configure BT to always show browser picker, or when certain keys are held (which is the default). More about this here: https://aloneguid.github.io/bt/picker.html

**Comment by ajhvdb** [comment]
I want to push the picker to come up and choose a different profile. So no rule but manually. Is this a big modification?

**Comment by ajhvdb** [comment]
i can modify the extension to add a second menuitem and modify:

const destUrl = BtProtoPrefix + url

to

const destUrl = BtProtoPrefix + '?' + url 

but have no knowledge of c++

**Comment by aloneguid** [comment]
From what I understand, you just need to set Browser Picker Mode to "always ask":

<img width="337" alt="image" src="https://github.com/aloneguid/bt/assets/3155189/5db608f4-422b-41ed-a178-d46dd8778500">

**Comment by ajhvdb** [comment]
sadly that only works from windows or apps in windows. From the browser we are missing the option to start the browser picker mode..

**Comment by aloneguid** [comment]
I have just tried and it works as advertised. Remember that BT can only intercept links if you click browser toolbar button or right-click a link and press "open with browser tamer". At least at the moment.
