### ISSUE TITLE
Links preprocessing

### ISSUE THREAD

**Issue by PsychodelEKS** [aloneguid/bt#57]
It would've been handy to have an option to pre-pocess URLs (preg replace) before applying any logic, for cases when the "old" URL stopped working due to domain/parameters changes and is not redirect automatically server-side.

**Comment by aloneguid** [comment]
It's possible, BT already has link processing pipeline, so it's a matter of exposing that in the UI. Can you give me an example you are working with?

**Comment by PsychodelEKS** [comment]
For now I wanted to replace this:
`https://sub_domain_1.domain.com/entity/13245`
with this:
`https://sub_domain_2.domain.com/entity/13245`
on the fly, before actually openning the link.

**Comment by aloneguid** [comment]
just some early prototype:
![image](https://github.com/aloneguid/bt/assets/3155189/55787d82-604e-4ef7-8ba7-efc3bbd232f9)

**Comment by PsychodelEKS** [comment]
> just some early prototype

looks good :)

**Comment by PsychodelEKS** [comment]
Works like a charm, thnx!
