### ISSUE TITLE
Add support for regex capture groups

### ISSUE THREAD

**Issue by Bluscream** [aloneguid/bt#63]
Example on [Github](https://gist.github.com/Bluscream/735d49e66a8f92f5fab1b6bad69f3f89#file-browserselector-ini)

So basically the rule `http?://domain.tld/path/(part_i_need)` and the browser can have arg `uri://other_path/(part_i_need)`

**Comment by aloneguid** [comment]
This is currently in progress, see #57 ;)

**Comment by Bluscream** [comment]
Closing as duplicate, thanks
