### ISSUE TITLE
Opening link with Chrome Private Profile does not open the link in Incognito window

### ISSUE THREAD

**Issue by magesh-memorres** [aloneguid/bt#66]
Opening the link with Chrome Private Profile does not open the link in the Incognito window
But when I select Edge (Chromium-based) it works fine.

Chrome version: `120.0.6099.216 (Official Build) (64-bit)`
Edge version: `120.0.2210.121 (Official build) (64-bit)`
Browser Tamer version: `3.6.2`
lmGui Version: `1.89.9 docking version`

### How to reproduce
1. Click any link 
2. Select the chrome private profile option

![image](https://github.com/aloneguid/bt/assets/127498032/90081b4b-4466-42a1-80a8-9d230b4a91cd)

This is my config.ini file

```config
fallback = chrome:Default
open_method = pick


[browser:firefox]
name = Mozilla Firefox
cmd = C:\Program Files\Mozilla Firefox\firefox.exe
hidden = n
subtype = firefox


[browser:firefox:Profile0]
name = Primary
arg = "%url%" -P "default-release"


[browser:firefox:private]
name = Private
arg = -private-window "%url%"
icon = C:\Program Files\Mozilla Firefox\firefox.exe
subtype = incognito
order = 1


[browser:chrome]
name = Google Chrome
cmd = C:\Program Files\Google\Chrome\Application\chrome.exe
hidden = n
subtype = chromium


[browser:chrome:Default]
name = Person 1
arg = "%url%" "--profile-directory=Default"


[browser:chrome:InPrivate]
name = Private
arg = "%url%" -inprivate
subtype = incognito
order = 1


[browser:msedge]
name = Microsoft Edge
cmd = C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
hidden = n
subtype = chromium


[browser:msedge:Default]
name = Personal
arg = "%url%" "--profile-directory=Default"
icon = C:\Users\username\AppData\Local\Microsoft\Edge\User Data\Default\Edge Profile Picture.png


[browser:msedge:InPrivate]
name = Private
arg = "%url%" -inprivate
subtype = incognito
order = 1


[popularity]
msedge:Default = 14
msedge:InPrivate = 1
chrome:Default = 48
chrome:InPrivate = 4

```

**Comment by magesh-memorres** [comment]
Updating the args helped to fix this. perhaps changing `-inprivate` to `-incognito` fixes this

![image](https://github.com/aloneguid/bt/assets/127498032/cfc1e8a4-8eb8-48be-b59d-f0752f66bf27)

**Comment by aloneguid** [comment]
Uh makes sense, thank you! I'll be adding the fix in the next patch.

**Comment by aloneguid** [comment]
Please try 3.7.2. You need to re- discover browsers to pick up updated configuration.

**Comment by magesh-memorres** [comment]
Yup works as expected. closing the issue.

Thanks for your work on this 🎉
