### ISSUE TITLE
Firefox extension omits `:` after `http(s)`

### ISSUE THREAD

**Issue by jnv** [aloneguid/bt#68]
## Steps to reproduce

1. Install BT extension for Firefox
2. Click the extension button on some website
3. Open link from BT in any browser

## Expected behavior

The new browser opens the original link.

## Actual behavior

The new browser opens the original link without `:` after `https`, resulting in connection error page, for example: `https//github.com`

## Notes

Since there were no recent releases of BT or the extension, I suspect this could be caused by very recent update of Firefox to v122. Extension in Edge seems unaffected.

Versions:

* Windows 11 Enterprise, Version 22H2, OS build 22621.3007
* Firefox 122.0 (64-bit)
* Extension: 1.2.1
* BT 3.6.2

**Comment by jnv** [comment]
Hmm, I'm thinking whether there was a change in URL handling mechanism:

https://github.com/aloneguid/bt/blob/4572ed22d537c298eb6faf81ef030489acf9bbbd/browser-extensions/firefox/background.js#L18-L20

The URL added after `x-bt://` isn't encoded, so it's possible Firefox trims the `:` character in order to perhaps prevent some security issue?

**Comment by aloneguid** [comment]
Thanks, I can reproduce this on my Firefox, and it used to work (nothing changed since then) so  it's definitely something in the Firefox itself. Will keep digging and come up with a fix.

**Comment by aloneguid** [comment]
I can confirm Firefox it removing `:` - the URL arrives to BT without it. 3.7.2 will fix this issue.

**Comment by aloneguid** [comment]
Please try installing 3.7.2. Firefox extension does not need an update.

**Comment by jnv** [comment]
Thank you Ivan! I'm off for a week, but will try it first thing once I'm back.

**Comment by jnv** [comment]
@aloneguid The fix works for me in BT v3.7.3. Thank you Ivan!
