### ISSUE TITLE
Firefox in BT container mode doesn't have option for "No container"

### ISSUE THREAD

**Issue by benaduggan** [aloneguid/bt#69]
It seems that when you activate container mode you have to pick a container tab rather than having all the containers as options in addition to a "No Container" option.

I use container tabs a lot for specific sites, but I also use the "no container" tab as my primary environment.

**Comment by aloneguid** [comment]
Makes sense, thanks. Will add this ASAP. Keep in mind that forefox may decide to assign a container implicitly if you don't specify one.  Let me play with this.

**Comment by benaduggan** [comment]
Thanks for looking into it! 

Also just wanted to say thanks for putting this out into the world! It's been a game a game-changer for me already. I would rather change my workflow than miss out on the benefits of this app!

**Comment by aloneguid** [comment]
Done in 3.7.3 ;)

**Comment by benaduggan** [comment]
You da best! Thanks! 😄
