### ISSUE TITLE
[Request] Ability to hide some browser profiles

### ISSUE THREAD

**Issue by ilapro53** [aloneguid/bt#71]
Now I can hide a few browsers, but I can’t hide specific profiles so that they do not display when choosing. I propose to make the possibility of hiding profiles as browsers.

**Comment by aloneguid** [comment]
No problem, makese perfect sense.

**Comment by majun** [comment]
For now, it is possible to delete unwanted profiles from the `config.ini' file.

**Comment by aloneguid** [comment]
This is coming next, you will have a new button on profile tab 
![image](https://github.com/user-attachments/assets/273a2150-0f47-4ef1-a825-e9ffbb902a4f)

**Comment by aloneguid** [comment]
released
