### ISSUE TITLE
[Request] Complex Matching with AND/OR 

### ISSUE THREAD

**Issue by luanfernandes** [aloneguid/bt#74]
Hi, as mentioned in Title, would it be possible to select if we want a "AND" or a "OR" when building up our rules? Guess the default now is "OR" for each rule, with the 'and' operator we would be able to get more complex.

My current situation: I use telegram to both talk to friends as well as work. I wanted a "and" operator to create a filter:

If from Telegram.exe AND this url matches > work browser ; Else if from telegram.exe > second browser;  Else, default browser.

Hope that makes sense!

**Comment by aloneguid** [comment]
I think it will make UI unnecessary complicated. But next version will support Lua scripting, which will solve this. I'll come back when it's ready to help you with the script.

**Comment by aloneguid** [comment]
It's supported in the latest release, see https://aloneguid.github.io/bt/scripting.html#printing-to-the-terminal
