### ISSUE TITLE
Priority feature

### ISSUE THREAD

**Issue by maluht** [aloneguid/bt#8]
The new priority feature is really great! But I think I have found a bug that I hope you can help with. I have "Browser Picker Mode" set to "Ask on Conflict". When I open a rule that match more then one rule, the picker is shown. I think that if one of the rules have a priority, that rule should be selected and the picker should not be shown.

I have also tried where I give all rules a priority, but the picker is still shown. It works perfectly if I set the "Browser Picker Mode" to "Never Ask", but that does not work for me. I would like to show the Picker, if I have not prioritized a rule.

Best Regards
Mads

**Comment by aloneguid** [comment]
As the picker is completely re-worked now, it's not relevant anymore.
