### ISSUE TITLE
Ability to open links to applications immediately in applications

### ISSUE THREAD

**Issue by Oguret2** [aloneguid/bt#80]
Good afternoon, just to give an example: they sent me a link to a message in discord in a telegram. On a phone, clicking on such a link immediately redirects the user to Discord (or will ask which browser to use, including Discord). On a PC, when you click on such a link, it should first open in the browser, and then the page in the browser will offer to redirect us to the already installed Discord application to open the link. those. To open a link to a message on any social network that has a desktop client (Telegram, Discord, WhatsApp, etc.) requires an extra step of opening the link in the browser and then in the desktop application.

So, is it possible to add these applications (discord, telegram, etc.) to browser tammer as one of the options for opening a link? Those. If I’m not in Discord (for example, in an email client), when I click on a link to Discord, I select Discord as the browser to open, does the link immediately open in it? I tried adding Discord and Telegram as browsers in browser tammer, but when I open a link in them, they simply expand, but do not go to the message to which the link points.

I hope I explained clearly) I'm waiting for an answer. And thank you for the amazing app 👍

**Comment by aloneguid** [comment]
Hi. How does the link to Discord look like? I suspect Discord registers it's own protocol handler in order to intercept those (I assume you have Discord desktop client installed?).

**Comment by Oguret2** [comment]
Sorry for the long answer. Yes, I have the discord client installed. Here is an example of a link to a message in a discord channel: https://discord.com/channels/1007626631059361792/1007659899477573652/1270053122831683658
