### ISSUE TITLE
Unable to disable persistent popularity sorting!

### ISSUE THREAD

**Issue by Dominiquini** [aloneguid/bt#83]
Even when the "Record number of clicks..." (persist_popularity = n) disabled, this app still save the number of times each browser is selected and always sort by this number!

Thanks!

**Comment by aloneguid** [comment]
This will be deprecated in v4 anyway, it will be something like:

![image](https://github.com/aloneguid/bt/assets/3155189/25e15882-3045-40b6-bd61-7eaa5d393986)

**Comment by aloneguid** [comment]
Released please try
