### ISSUE TITLE
[Feature Request] Option to dismiss picker window on focus loss

### ISSUE THREAD

**Issue by rp1231** [aloneguid/bt#86]
Right now if you don't close the picker window manually using the x button, it lingers on and I find a few of them in the background.
It would be great if an option could be added whereby you can change the behavior of the picker window to be dismissed on focus loss.
Thanks

**Comment by aloneguid** [comment]
Agreed, thanks for the suggestion.

I'll have to make it an option as not everyone may need it i.e. I might want to change to focus to check something and come back.

I'll also add an option to dismiss on Escape key.

**Comment by aloneguid** [comment]
it's coming in the next version 
![image](https://github.com/user-attachments/assets/20ca0b84-bf49-4dd9-aa0f-8b42e83c2707)

**Comment by aloneguid** [comment]
Released in 4.1.1

**Comment by aloneguid** [comment]
Just checking if you have enabled it in the options, it's off by default. Try to close configuration window so BT saves the configuration, and try again?

**Comment by aloneguid** [comment]
wait! i found the issue, it was between the screen and my chair. Building the fix...

**Comment by aloneguid** [comment]
Please check v4.1.2.
