### ISSUE TITLE
[Bug] No longer able to launch links from Slack (process stays in background leaking memory)

### ISSUE THREAD

**Issue by maddada** [aloneguid/bt#93]
Thank you for all the amazing work you're doing on browser tamer, this app is a must have!

**Problem:**
After the last update I'm no longer seeing the profile selection pop-up when clicking on a link inside slack. 

When checking the task manager I see a Browser Tamer background process for each time I clicked a link in slack, and these processes never exit, don't show up in the taskbar or alt+tab switcher, and the more you have the laggier the pc gets.

![image](https://github.com/user-attachments/assets/6b1e800e-9827-469e-a2cb-3e07ef3ed2d4)

I didn't find any other apps that have this issue so far.

Workaround is to copy link location and paste it 

Wish I could contribute a fix but I'm not experienced with c or cpp :/
All the best

**Comment by aloneguid** [comment]
Sorry that's probably latest AI features. If you don't mind rolling back I'll fix in the next release.

**Comment by maddada** [comment]
No worries, I need the other bug fixes in the latest version, so I'll stay on latest and deal. Hope it's not too difficult to solve.

Thank you for all of the great work!

**Comment by aloneguid** [comment]
fixed in 4.1.0

**Comment by maddada** [comment]
@aloneguid Thank you so much! You're a life saver ❤️
