### ISSUE TITLE
[Bug] BT should alert when trying to launch an executable that does not exist.

### ISSUE THREAD

**Issue by AJolly** [aloneguid/bt#98]
Edge case:
BT should alert when its trying to launch a browser that does not exist. 

I got hit with this because of portable mode, and syncing my bt between two computers.
config.ini includes:

`[browser:brave]
name = Brave
cmd = "C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe"
hidden = n
subtype = chromium
`
Which works fine, except on one machine Brave installed itself to C:\Program Files **(x86)**\BraveSoftware\Brave-Browser\Application\brave.exe instead of C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe

Took me a while to debug!

**Comment by aloneguid** [comment]
Fixed in 4.2.1
